### ISSUE TITLE
Why one should use akryl-store instead of Redux or MobX?

### ISSUE THREAD

**Issue by strangecamelcaselogin** [akryl-kt/akryl-store#1]

**Comment by ashlanderr** [comment]
Akryl-store is based on built-in Akryl reactivity:
- You don't need any wrappers around components. 
- All reactive hooks will work out of the box.

I think you can use Redux or MobX, but you have to write wrappers for them. Redux for me is too much boilerplate, but it will probably work. 

MobX is more complicated. It's not optimized for Kotlin data structures. For example, HashMap consists of many JS objects and all of them will be wrapped into observable. Also, MobX uses Proxy, so it will change references to internal objects of HashMap, that can cause issues in some cases. 

Akryl reactivity modifying Kotlin objects in-place, so references are staying the same. You can see the algorithm [here](https://github.com/akryl-kt/akryl-core/blob/0971248150eac0f1755372361634ae4839ef2a98/src/main/kotlin/io/akryl/rx/Observable.kt#L82).

**Comment by strangecamelcaselogin** [comment]
Thanks!
